version: '3'

services:
  vulnerable-web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./restricted:/app/restricted
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
