version: '3'

services:
  vulnerable-web-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./restricted:/app/restricted
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0 # Turn off debug mode in production
      - SECRET_KEY=${SECRET_KEY:-default_secret_key} # Use env variable or default
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
